Update GMT paper
gmt-china/GMT_docs pull request #729
Opened 2021-08-08 23:52 UTC by seisman

2021-08-09 04:45 UTC, seisman commented on source/basis/paper.rst
> +        gmt ...
我比较犹豫，这一节的示例，是按照现在的写法，给出一个框架 （即 ``gmt ...``） 还是给出具体的某个命令（比如 ``gmt basemap``）。

后者的优点在于，用户可以直接执行命令理解其输出。

2021-08-09 05:17 UTC, core-man commented on source/basis/paper.rst
> +        gmt ...
我比较喜欢实际例子，我觉得使用 GMT 的用户应该能举一反三，知道可以适用于其他命令。

2021-08-15 23:31 UTC, seisman commented on source/basis/paper.rst
> +.. figure:: https://docs.gmt-china.org/5.4/_images/paper-gmtplot-1.png
@core-man This PR is almost ready for review. The only missing part is a better figure showing the position of the plot origin on the full-size GMT paper.

I'll work on the image if you think the other parts are all OK.

2021-08-17 04:11 UTC, seisman commented
![map](https://user-images.githubusercontent.com/3974108/129662085-62875cc5-05b4-4123-a431-687cddfd89d9.png)

I added this figure to explain the relative positioning of plot origin on a "full-size" paper.

2021-08-17 05:56 UTC, core-man commented on source/basis/paper.rst
>  :term:`PS_MEDIA` 来指定纸张尺寸::
```suggestion
因而用户无需关心画布大小。若需要生成特定尺寸的图片，而不裁剪周边的白色区域，
可以修改 GMT 参数 :term:`PS_MEDIA` 来指定纸张尺寸::
```

2021-08-17 05:56 UTC, core-man commented on source/basis/paper.rst
>  GMT 支持多种矢量图片格式和位图图片格式。
```suggestion
GMT 支持多种矢量图片格式和位图图片格式：
```

2021-08-17 05:56 UTC, core-man commented on source/basis/paper.rst
> +JPG [**推荐**]、BMP、PPM 和 TIFF 格式。
```suggestion
- 矢量图片格式包括 PDF [**推荐**]、PS 和 EPS 格式；
- 位图图片格式包括 PNG [**推荐**]、JPG [**推荐**]、BMP、PPM 和 TIFF 格式。
```

2021-08-17 05:58 UTC, core-man approved these changes

2021-08-17 14:04 UTC, core-man approved these changes

2021-08-18 15:39 UTC, seisman commented
@core-man I renamed the file name from `paper.rst` to `canvas.rst` because "canvas" is the correct name. The PR now is a little difficult to review due to the file name change, so you have to read the whole section again.

The script used to generate the figure is also added to this repository, but the script is neither executed by the gmtplot directive, nor shown in the documentation. It's included in the repo to make sure that we can reproduce the image in the future.

2021-09-09 01:17 UTC, seisman commented
Ping @core-man for review.

2021-09-09 01:22 UTC, wangliang1989 commented on source/basis/canvas.rst
> +GMT 在绘图时，默认的绘图原点位于画布（11.6 米宽、11.6 米高）的左下角 (12.7 cm, 12.7 cm) 处
初学者可能不理解什么是绘图原点。应该先陈述绘图原点的定义，再说它在哪

2021-09-09 05:56 UTC, seisman commented on source/basis/canvas.rst
> +GMT 在绘图时，默认的绘图原点位于画布（11.6 米宽、11.6 米高）的左下角 (12.7 cm, 12.7 cm) 处
Fixed in a18acff4.

2021-09-09 08:08 UTC, wangliang1989 requested changes

2021-09-09 08:08 UTC, wangliang1989 commented on source/basis/canvas.rst
> +GMT 在绘图时，默认的绘图原点（即底图边框左下角）位于画布（11.6 米宽、11.6 米高）的
**前面解释底图了吗？**
```suggestion
绘图原点是指底图的左下角。默认的绘图原点（即底图边框左下角）位于画布（11.6 米宽、11.6 米高）的
```

2021-09-09 08:18 UTC, seisman commented on source/basis/canvas.rst
> +GMT 在绘图时，默认的绘图原点（即底图边框左下角）位于画布（11.6 米宽、11.6 米高）的
默认读者知道底图

2021-09-09 08:20 UTC, wangliang1989 commented on source/basis/canvas.rst
> +GMT 在绘图时，默认的绘图原点（即底图边框左下角）位于画布（11.6 米宽、11.6 米高）的
我觉得他很可能不知道何为底图

2021-09-20 13:57 UTC, merged